version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: phonebook_clean_arquitecture
    restart: always

  phonebook-app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://YyldJPxAwdPKrKVICFjMAAkGpHnK7SGm@dpg-cqk37raju9rs738fu8dg-a.oregon-postgres.render.com:5432/phonebook_clean_arquitecture
      SPRING_DATASOURCE_USERNAME: phonebook_clean_arquitecture_user
      SPRING_DATASOURCE_PASSWORD: YyldJPxAwdPKrKVICFjMAAkGpHnK7SGm
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8089:8080"